use_frameworks!

target 'phrase_swift_Example' do
  pod 'phrase_swift', :path => '../'

  target 'phrase_swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
